# AWS
# AWS_ACCESS_KEY_ID: 'AKIAIGZWIR6GB56FDLPA'
# AWS_SECRET_ACCESS_KEY: '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'

# LOSANT CONFIG
LOSANT_APP_ID: '590bc7a2c8f13000014788c5'
LOSANT_ACCESS_KEY: '5604c1f7-fd1a-46b9-a3b5-ff2a455a368b'
LOSANT_ACCESS_SECRET_KEY: '3ef1f8fe40abed958e5f3455d797785b19134b8a9e0ff5463521ffdda935fb16'
#LOSANT_API_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1OTFhOTk2YmU4N2YyYTAwMDFlNmY3OWYiLCJzdWJ0eXBlIjoiYXBpVG9rZW4iLCJzY29wZSI6WyJhbGwuQXBwbGljYXRpb24iXSwiaWF0IjoxNDk0OTE1NDM1LCJpc3MiOiJhcGkuZ2V0c3RydWN0dXJlLmlvIn0.Tjnqzpl2LS9V6-Z7-XxhOrkCmvLcOBCOlOIuFzfC0Gc'

LOSANT_API_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1OTExMGY4NDgxNmZmZjAwMDFiOTI0M2UiLCJzdWJ0eXBlIjoidXNlciIsInNjb3BlIjpbImFsbC5Vc2VyIl0sImlhdCI6MTQ5NTI1OTM4NiwiaXNzIjoiYXBpLmdldHN0cnVjdHVyZS5pbyJ9.hdU4K2vqXNNTIb6d9EX-ozkzvLjcepfXFi7dBgjzL4A'